### ISSUE TITLE
TypeError: 'NetSpec' object does not support item assignment

### ISSUE THREAD

**Issue by yangyi02** [beijbom/beijbom_python_lib#1]
Hello, I tried to use your beijbom_caffe_tools.residual_net() to create the residual net for Caffe training, however, the system resports an error as below:

Do you have advice on fixing this problem?

Thanks!

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-9fca94c76161> in <module>()
----> 1 a = residual_net(18, 'data')

tools/beijbom_python_lib/beijbom_caffe_tools.py in residual_net(total_depth, data_layer_params, num_classes, acclayer)
    677             s = str(nout) + '_' + str(unit) + '_' # layer name prefix
    678             if unit_type == "standard":
--> 679                 residual_standard_unit(n, nout, s, newdepth = unit is 1 and nout > 64)
    680             else:
    681                 residual_bottleneck_unit(n, nout, s, newdepth = unit is 1)

tools/beijbom_python_lib/beijbom_caffe_tools.py in residual_standard_unit(n, nout, s, newdepth)
    612     stride = 2 if newdepth else 1
    613 
--> 614     n[s + 'conv1'], n[s + 'bn1'], n[s + 'lrn1'] = conv_bn(bottom, ks = 3, stride = stride, nout = nout, pad = 1)
    615     n[s + 'relu1'] = L.ReLU(s + 'lrn1', in_place=True)
    616     n[s + 'conv2'], n[s + 'bn2'], n[s + 'lrn2'] = conv_bn(s + 'relu1', ks = 3, stride = 1, nout = nout, pad = 1)

TypeError: 'NetSpec' object does not support item assignment

**Comment by DirtyMaster** [comment]
Hi, 
You should replace all n[...] by n.__dict__['tops'][...], it worked for me!

**Comment by beijbom** [comment]
Hi guys,

yeah, that'll work. Or add:

+    def __getitem__(self, name):
+        return self.tops[name]
+
+    def __setitem__(self, name, value):
+        self.tops[name] = value
+

to net_spec.py in $CAFFEHOME/python/caffe directory. Then the original code runs. Please be aware that the residual nets don't train properly with the version of the batchnorm currently on the caffe main branch. We are working on it! If you do get them to work, please let us know.

cheers

**Comment by egadeski** [comment]
Is there an opened issue on the caffe repo about this?

**Comment by beijbom** [comment]
No. This this is just a simple hack for convenience, and not really an issue with caffe. Once we get the residual nets to run and we add it as an tutorial or to the model zoo, we can worry about adding those lines formally.

**Comment by thuhuwei** [comment]
Hi, @beijbom , I trained a residual net on cifar10 in these days, and meet a problem: the training accuracy is obviously higher than the test accuracy. Is'it caused by the batch norm layer? Since if I set use_global_stats (batch norm layers) false, these two accuracy values are very closed.

**Comment by n3011** [comment]
@beijbom @thuhuwei  did u get residual net working with caffe?

**Comment by thuhuwei** [comment]
@n3011 , Please visit my forked caffe, and see python generateResNet.py (only nets on cifar10 is provided) . Another implementation of the Batch Normalization Layer is used, and our 32-layer ResNet achieves 91%  accuracy on cifar10, lower than the paper.

**Comment by beijbom** [comment]
@n3011 , the current version compiles and trains, but it's not learning quite as it should. I'll make sure to ping this thread once I have a stable version.

**Comment by egadeski** [comment]
Hi,
I'm training the 101-layer deep ResNet with the same hyperparameters as in the paper and caffe's master branch BatchNorm layer. After 345,000 iterations, the top-1 error is 28% on validation set.

**Comment by thuhuwei** [comment]
@egadeski , I cannot get good accuracy on cifar10 with the batchnorm layer in caffe's master branch. I don't know the reason.

**Comment by n3011** [comment]
@thuhuwei Thanks, I will look on it. 
@beijbom Thanks.

**Comment by thuhuwei** [comment]
@beijbom ,  @egadeski , I tried to train ImageNet with a 50-layer ResNet. However, I found that memory required is more than 12G even with batch-size = 32, and got the "cuda :: out of memory" err. Did you meet this problem?

**Comment by beijbom** [comment]
That is a bit strange: I was able to use a batch size of 80 on a 12G Titan X.

**Comment by thuhuwei** [comment]
Thanks for this message. I think it might be caused by our used batch normal layer, which is memory consuming.
