### ISSUE TITLE
how to use it or give a generated .prototxt

### ISSUE THREAD

**Issue by freesouls** [beijbom/beijbom_python_lib#2]
hi, can you give a readme that tells how we can use the scripts or can you give me a generated .prototxt for example, you can give a network has about 40 layers, I just want to see how you connect the shortcuts, and the details of when to use batch normalization and relu.

Thanks in advance

**Comment by beijbom** [comment]
I suppose you refer to the residual nets? Just call

n = residual_net(total_depth, data_layer_params, num_classes = 1000, acclayer = True)

and then store str(n.to_proto()) to a net.prototxt file and use with caffe. Please know that these nets do not yet train with the main caffe branch.
